# Generated by Django 4.0 on 2024-05-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
