# Generated by Django 4.0 on 2024-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
